# Use the official PostgreSQL 9.6 Alpine image as the base image
FROM postgres:9.6-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=kanban
ENV POSTGRES_USER=kanban
ENV POSTGRES_PASSWORD=kanban

# Expose the PostgreSQL port
EXPOSE 5432



